Komis/Controllers/OpiniaController.cs
using Komis.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Komis.Controllers
{
    [Authorize]
    public class OpiniaController : Controller
    {
        private readonly IOpiniaRepository _opiniaRepository;

        public OpiniaController(IOpiniaRepository opiniaRepository)
        {
            _opiniaRepository = opiniaRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Opinia opinia)
        {
            if (ModelState.IsValid)
            {
                _opiniaRepository.DodajOpinie(opinia);
                return RedirectToAction("OpiniaWyslana");
            }
            return View(opinia);
        }

        public IActionResult OpiniaWyslana()
        {
            return View();
        }
    }
}

Komis/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>
@inject SignInManager<IdentityUser> SignInManager

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/content/site.css" rel="stylesheet" />

    <title>@ViewBag.Title</title>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index" class="navbar-brand">Komis</a></li>
                    <li><a asp-controller="Opinia" asp-action="Index">Opinia</a></li>
                </ul>

                @if (SignInManager.IsSignedIn(User))
                {
                    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
                          method="post" class="navbar-right">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Wyloguj</a></li>
                        </ul>
                    </form>
                }
                else
                {
                    <ul class="nav navbar-nav">
                        <li><a id="registerLink" asp-controller="Account" asp-action="Register">Rejestracja</a></li>
                        <li><a id="loginLink" asp-controller="Account" asp-action="Login">Logowanie</a></li>
                    </ul>
                }

            </div>
        </div>
    </nav>

    <div class="container body-content">
        <div class="row">
            @RenderBody()
        </div>
    </div>
</body>
</html>